### ISSUE TITLE
front-end track courses to be completed

### ISSUE THREAD

**Issue by Tapedigo** [Tapedigo/Treehouse#2]
## TODO

*Courses left to complete the Treehouse front-end development track*
* [ ] Github basics 
* [ ] Debugging CSS with chrome dev tools
* [ ] Responsive layout
* [ ] Practice media queries
* [ ] CSS flexbox layout
* [ ] HTML forms
* [ ] Pratice basic variables, input and output
* [ ] Javascript 
* [ ] Javascript numbers
* [ ] Javascript loops, arrays, and objects
* [ ] Css selectors
* [ ] Web accessibility compliance
* [ ] website optimization
* [ ] HTML tables
* [ ] CSS grid layout
* [ ] Build a responsive navigation with flexbox
* [ ] Javascript and DOM
* [ ] jquery basics
* [ ] Bootstrap 4 basics
😀 🎊
